@startuml
!theme reddress-lightred
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Client - Server - Architecture Overview

' LAYOUT_WITH_LEGEND()

Person(user, "User")
Container(browser, "Browser", "Client")
System_Boundary(site, "Servlet container", "HTTP server"){
    System(webapp, "Drink Advisor App", "Web App", "Servlet")
}
ContainerDb(database, "Database", "DB")

Rel(user, browser, "Action")
Rel(browser, webapp, "Request")
Rel(webapp, browser, "Response")
BiRel(webapp, database, "Data")

footer David Ramirez - drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()
@enduml